version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Application port
      - "9090:9090"  # Metrics port
    volumes:
      - .:/app
      - ./logs:/var/log/logging_service
    env_file:
      - .env.development
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - logging_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - logging_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  logging_network:
    driver: bridge

volumes:
  redis_data:
  logs: 